### PR TITLE
preselections metadata

### PR DESCRIPTION
**Pull request by wschidol**
The next version of ISO/IEC 14496-12 is poised to add structures to represent preselections through codec-agnostic metadata. This PR adds support for the meta, grpl, prsl, ardi, elng, and labl boxes. Along the way, a new datatype `utf8string` is provided to be able to correctly interpret UTF8 strings. All boxes have unit tests provided against them.

This source code is provided for review and reference even though the PR is not meant to be merged back just yet. We suggest keeping the PR in draft stage until the specification goes into FDIS stage, hopefully sometime this summer.

### CODE REVIEW

**Comment by dsilhavy** [comment]
Thanks @wschidol we don't really have a maintainer for this project, but I will try to check in between. Maybe @bbert also has a comment.

**Comment by bbert** [comment]
Thanks @wschidol , I don't have the next ISO/IEC 14496-12 spec but as soon as it is available in FDIS stage I can review this PR

**Comment by wschidol** [comment]
Makes sense, thanks a lot! I'll come back to this thread once we have FDIS.

**Comment by wschidol** [comment]
#59 obsoletes this pull request.

**Pull request closed without merging**
